### ISSUE TITLE
Multiple order by

### ISSUE THREAD

**Issue by radic4** [juampi92/cursor-pagination#9]
Hello,

I have some problems and don't know how to implement this package and don't know if its even possible.

I have posts list and i have 3 possible ways to sort these posts.
1: ID descending (most relevant)
2: by distance (calculated dynamically based on lat and long in posts table and lat and long of user querying results) (it will sort by ID descending too, because distance can be same for multiple posts in some cases)
3: by most participants (users can participate to posts) (it will sort by ID descending too, because number of participants will have a lot of duplicates)

Is there any way to implement this cursor pagination?

I know it will work as expected in case number 1 because ID is unique, but it also says it will not work as expected in case 2 and 3 because first order by column can have duplicate values.

Is there any workaround for this so i can use this package for this purpose? Maybe something like having cursor based on all order by columns or something like that?

**Comment by juampi92** [comment]
I'm afraid that if you have a lot of duplicates, this won't work properly.

So, what does package does basically is instead of running a query with the limit and offset (like a pagination query would do), it's grabbing a column and saying `WHERE column > last_value LIMIT 10`.

So if you have duplicates, and you have 15 elements that have the same value (for example 'a'), the query will grab the first 10, and then for the next page will do `WHERE column > a LIMIT 10`, so the other 5 of 'a' would not show.

This works best for fixed things like created_at dates, or unique `id`.
Pagination with LIMIT and OFFSET might be the thing for you

**Comment by trevorgehman** [comment]
@radic4 this package is also available if you need to order by multiple columns: https://github.com/amrnn/laravel-cursor-paginator
